export const NOTIFICATION_TYPES = {
  AUTH: 'AUTH',
  
  // KYC Events
  KYC_SUBMITTED: 'KYC_SUBMITTED',
  KYC_APPROVED: 'KYC_APPROVED',
  KYC_REJECTED: 'KYC_REJECTED',
  
  // Subscription Events
  SUBSCRIPTION_CREATED: 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_EXPIRING: 'SUBSCRIPTION_EXPIRING',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  
  // Order Events
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_PROCESSING: 'ORDER_PROCESSING',
  ORDER_PACKED: 'ORDER_PACKED',
  ORDER_DISPATCHED: 'ORDER_DISPATCHED',
  ORDER_OUT_FOR_DELIVERY: 'ORDER_OUT_FOR_DELIVERY',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  
  // Payment Events
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  
  // Delivery Events
  DELIVERY_ASSIGNED: 'DELIVERY_ASSIGNED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  
  // Commission & Coin Events
  COMMISSION_EARNED: 'COMMISSION_EARNED',
  COIN_EARNED: 'COIN_EARNED',
  
  // Referral & Spin Events
  SPIN_REWARD: 'SPIN_REWARD',
  REFERRAL_JOINED: 'REFERRAL_JOINED',
  REFERRAL_REWARD: 'REFERRAL_REWARD',
  
  // Shop Events
  SHOP_ACTIVATED: 'SHOP_ACTIVATED',
  SHOP_SUSPENDED: 'SHOP_SUSPENDED',
  
  // Return Events
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  RETURN_APPROVED: 'RETURN_APPROVED',
  RETURN_REJECTED: 'RETURN_REJECTED',
  RETURN_COMPLETED: 'RETURN_COMPLETED',
};
