export const PRIMARY_ROLES = {
  CUSTOMER: 'CUSTOMER',
  VENDOR: 'VENDOR',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
};

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  VENDOR: 'VENDOR',
  CUSTOMER: 'CUSTOMER',
  USER: 'CUSTOMER', // Backward-compatibility alias resolving to canonical CUSTOMER
  STATE_FRANCHISE: 'STATE_FRANCHISE',
  DISTRICT_FRANCHISE: 'DISTRICT_FRANCHISE',
  TALUK_FRANCHISE: 'TALUK_FRANCHISE',
  SHOPKEEPER: 'SHOPKEEPER',
  DELIVERY_PARTNER: 'DELIVERY_PARTNER',
  HUB_STAFF: 'HUB_STAFF',
  STAFF: 'STAFF',
  DOCTOR: 'DOCTOR',
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  BLOCKED: 'BLOCKED',
  PENDING: 'PENDING',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
};

