export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  STATE_FRANCHISE: 'STATE_FRANCHISE',
  DISTRICT_FRANCHISE: 'DISTRICT_FRANCHISE',
  TALUK_FRANCHISE: 'TALUK_FRANCHISE',
  SHOPKEEPER: 'SHOPKEEPER',
  VENDOR: 'VENDOR',
  USER: 'USER',
  CUSTOMER: 'CUSTOMER',
  DELIVERY_PARTNER: 'DELIVERY_PARTNER',
  HUB_STAFF: 'HUB_STAFF',
  STAFF: 'STAFF',
  DOCTOR: 'DOCTOR',
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
};
